[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && playwright install --with-deps chromium"

[deploy]
startCommand = "python bot.py"
restartPolicyType = "on_failure"

[variables]
PYTHONUNBUFFERED = "1"
PLAYWRIGHT_BROWSERS_PATH = "/app/pw-cache"
